title: Rizchel Masong
logo: /assets/img/logo_1.jpg
email: rizchel_masong@dlsu.edu.ph
description: Your AI Officer and Radio Astronomer.
favicon: true
color-scheme: auto

navigation:
  - name: Home
    link: ./index.html
  - name: Research
    sublist:
      - name: Highlights
        link: ./index.html
      - name: Statements
        link: ./index.html
  - name: Teaching
    link: ./index.html
  - name: Bio
    link: ./index.html
  - name: Contact
    link: ./index.html

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/masongrizchel
  - name: Google Scholar
    icon: <i class="fa-brands fa-google-scholar"></i>
  - name: ORCID
    link: https://orcid.org/my-orcid?orcid=0000-0001-9839-4412
    icon: <i class="fa-brands fa-orcid"></i>
  - name: Ko-fi
    icon: <i class="fas fa-mug-hot ko-fi"></i>
    link: https://www.ko-fi.com/simasongcute
  - name: Tumblr
    icon: <i class="fa-brands fa-square-tumblr"></i>
    link: https://masongrizchel.tumblr.com
  - name: Spotify
    icon: <i class="fa-brands fa-spotify"></i>
    link: https://open.spotify.com/show/5YBqmxhXJQTXDlDrpMImNV?si=7f76c1e87ee540da
  - name: Patreon
    icon: <i class="fa-brands fa-patreon"></i>
    link: https://www.patreon.com/simasongcute

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
