title: Rizchel Masong
logo: /assets/img/logo_1.jpg

email: rizchel_masong@dlsu.edu.ph
email: rizchel.masong@globalcomfortgroup.com

description: Your AI Officer and Radio Astronomer.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/masongrizchel
  - name: Ko-fi
    icon: <i class="fas fa-mug-hot ko-fi"></i>
    link: https://www.kofi.com/simasongcute
  - name: Tumblr
    icon: <i class="fa fa-tumblr" aria-hidden="true"></i>
  - name: Spotify
    icon: <i class="fa fa-spotify" aria-hidden="true"></i>


navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
